# [START deployment_yaml]
imports:
  - path: cromwell.jinja

resources:
  - name: cromwell
    type: cromwell.jinja
    properties:
      cromwell_db_ip: "34.68.25.189"
      cromwell_db_password: "foobarbaazbuux"
      cromwell_service_mem: 11
      cromwell_version: 39
      region: us-central1
      vm_boot_disk_size: 10
      vm_machine_type: n1-standard-4
      vm_name: cromwell
      vm_service_account: "cromwell-server@griffith-lab.iam.gserviceaccount.com"
      vm_static_ip_address: "35.188.155.31"
      vm_subnetwork: "https://www.googleapis.com/compute/v1/projects/griffith-lab/regions/us-central1/subnetworks/cromwell"
      zone: us-central1-c
# [END deployment_yaml]
